### PR TITLE
i added my program about BruteForceDivideConquer

### PR DESCRIPTION
**Pull request by alimurrofid**
please accept my pull request

### CODE REVIEW

**Comment by sumanmeher** [comment]
You know this counts as only 1 PR

**Comment by alimurrofid** [comment]
> You know this counts as only 1 PR

yes it's okay sir please agree to my pull request to join this hacktoberfest event

**Comment by sumanmeher** [comment]
ok

**Comment by sumanmeher** [comment]
Do give a star to my repo.

**Comment by alimurrofid** [comment]
thank you sir for your repo I have given a star

**Comment by sumanmeher** [comment]
thank you

**Pull request merged**
