### PR TITLE
odd_even by subhagata

### PR DESCRIPTION
**Pull request by subhagataa**
thank you for reading my request! I am a 1st year student with no much idea about coding, I am here to experience and learn. i am trying my best to cope up.

### CODE REVIEW

**Comment by subhagataa** [comment]
@sumanmeher please review

**Comment by sumanmeher** [comment]
Make a folder and put the code in it and push. It's written clearly in the readme. Follow the instructions carefully.

**Comment by subhagataa** [comment]
okk..I'm so sorry, I'll do it again

**Comment by subhagataa** [comment]
I did it. @sumanmeher

**Comment by sumanmeher** [comment]
Follow the instructions. You haven't written your name and username in your file. Read the readme carefully.

**Comment by sumanmeher** [comment]
From next time onwards write your name and username.

**Comment by subhagataa** [comment]
thank you so muchh.. I surely will.

**Pull request merged**
